import { CategoryId } from "@/types/category.types";
import { TemplateMeta } from "@/types/template.types";

export const TEMPLATES: TemplateMeta[] = [
  // ----------------------------------------------------
  // Gold Category (10 Templates)
  // ----------------------------------------------------
  {
    id: "gold-classic-jewellers",
    name: "Classic Jewellers",
    category: "gold",
    description: "Traditional high-end jewellery invoice with ornate gold borders, hallmark section, and itemized making charges.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "amber",
    badge: "Most Popular",
  },
  {
    id: "gold-royal-zari",
    name: "Royal Zari",
    category: "gold",
    description: "Opulent regal motif layout with deep gold accents, perfect for bridal and high-value gold ornaments.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "amber",
    badge: "Luxury",
  },
  {
    id: "gold-minimal-karat",
    name: "Minimal Karat",
    category: "gold",
    description: "Clean modern layout emphasizing purity ratings, net weight calculations, and tax breakdown.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "amber",
  },
  {
    id: "gold-hallmark-ledger",
    name: "Hallmark Ledger",
    category: "gold",
    description: "Structured table emphasizing HUID codes, BIS hallmark stamps, and old gold exchange credits.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "amber",
    badge: "Certified",
  },
  {
    id: "gold-vintage-ornate",
    name: "Vintage Ornate",
    category: "gold",
    description: "Heritage aesthetic inspired by traditional Indian goldsmith ledgers with decorative headers.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "amber",
  },
  {
    id: "gold-modern-boutique",
    name: "Modern Boutique",
    category: "gold",
    description: "Sleek designer invoice with contemporary typography for luxury gold boutiques and studio jewellers.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "amber",
  },
  {
    id: "gold-temple-gold",
    name: "Temple Gold",
    category: "gold",
    description: "Traditional South & North Indian temple jewellery format with dedicated columns for gross/net weight and stones.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "amber",
  },
  {
    id: "gold-bridal-collection",
    name: "Bridal Collection",
    category: "gold",
    description: "Comprehensive multi-item wedding set invoice with detailed itemization for necklace, bangles, and earrings.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "amber",
  },
  {
    id: "gold-bullion-simple",
    name: "Bullion Simple",
    category: "gold",
    description: "Focused single-screen layout for 24K gold coins, minted bars, and raw bullion sales.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "amber",
  },
  {
    id: "gold-compact-counter",
    name: "Compact Counter",
    category: "gold",
    description: "Space-efficient A5 compact invoice for quick retail counter sales and immediate billing.",
    paperSize: "A5",
    isThermal: false,
    themeColor: "amber",
    badge: "Fast Counter",
  },

  // ----------------------------------------------------
  // Silver Category (10 Templates)
  // ----------------------------------------------------
  {
    id: "silver-silverline-classic",
    name: "Silverline Classic",
    category: "silver",
    description: "Elegant silver-toned template with structured weight, purity, and hallmark details.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "slate",
    badge: "Most Popular",
  },
  {
    id: "silver-filigree-frame",
    name: "Filigree Frame",
    category: "silver",
    description: "Tailored for delicate Cuttack/Karimnagar filigree work with 1.5% special GST tax support.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "slate",
    badge: "Filigree Spec",
  },
  {
    id: "silver-modern-mint",
    name: "Modern Mint",
    category: "silver",
    description: "Refined aesthetic for 999 fine silver bars, coins, and corporate gifting.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "slate",
  },
  {
    id: "silver-ledger-pure",
    name: "Ledger Pure",
    category: "silver",
    description: "Clean tabular layout for silver utensils, dining sets, pooja articles, and giftware.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "slate",
  },
  {
    id: "silver-temple-silver",
    name: "Temple Silver",
    category: "silver",
    description: "Designed for religious silver idols, kalash, pooja items, and heavy silver crafts.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "slate",
  },
  {
    id: "silver-rustic-artisan",
    name: "Rustic Artisan",
    category: "silver",
    description: "Warm artisan layout for handcrafted tribal and oxidized silver jewellery.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "slate",
  },
  {
    id: "silver-coin-bar",
    name: "Coin & Bar",
    category: "silver",
    description: "Streamlined bill for 10g/50g/100g/1kg silver coins and investment bullion.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "slate",
  },
  {
    id: "silver-minimal-sterling",
    name: "Minimal Sterling",
    category: "silver",
    description: "Minimalist 925 Sterling jewellery invoice for e-commerce and modern high-street brands.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "slate",
  },
  {
    id: "silver-boutique-silver",
    name: "Boutique Silver",
    category: "silver",
    description: "Chic luxury layout with brand banner and custom notes for gift packaging.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "slate",
  },
  {
    id: "silver-compact-counter",
    name: "Compact Counter",
    category: "silver",
    description: "Quick A5 counter slip for instant customer walk-in billing.",
    paperSize: "A5",
    isThermal: false,
    themeColor: "slate",
    badge: "Compact",
  },

  // ----------------------------------------------------
  // Grocery Category (10 Templates)
  // ----------------------------------------------------
  {
    id: "grocery-kirana-classic",
    name: "Kirana Classic",
    category: "grocery",
    description: "Standard full-page A4 grocery invoice with packaged/loose tags and clear GST rate column.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "emerald",
    badge: "Standard A4",
  },
  {
    id: "grocery-fresh-mart",
    name: "Fresh Mart",
    category: "grocery",
    description: "Modern supermarket bill layout with savings/discounts highlight and barcode summary.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "emerald",
  },
  {
    id: "grocery-thermal-80mm",
    name: "Thermal 80mm",
    category: "grocery",
    description: "Optimized 80mm POS receipt layout for ESC/POS thermal printers with compact items and UPI QR code.",
    paperSize: "Thermal-80mm",
    isThermal: true,
    themeColor: "emerald",
    badge: "POS 80mm",
  },
  {
    id: "grocery-thermal-58mm",
    name: "Thermal 58mm",
    category: "grocery",
    description: "Ultra-compact 58mm mini POS receipt layout for handheld thermal billing machines.",
    paperSize: "Thermal-58mm",
    isThermal: true,
    themeColor: "emerald",
    badge: "Mini POS 58mm",
  },
  {
    id: "grocery-wholesale-ledger",
    name: "Wholesale Ledger",
    category: "grocery",
    description: "Detailed wholesale B2B grocery bill with bag counts, quintal rates, and HSN-wise tax breakdown.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "emerald",
    badge: "Wholesale",
  },
  {
    id: "grocery-daily-needs",
    name: "Daily Needs",
    category: "grocery",
    description: "Clean neighborhood provision store bill with unit breakdown (kg/g/L/packet).",
    paperSize: "A4",
    isThermal: false,
    themeColor: "emerald",
  },
  {
    id: "grocery-farm-fresh",
    name: "Farm Fresh",
    category: "grocery",
    description: "Organic and fresh produce invoice with zero-GST exempt produce highlight.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "emerald",
  },
  {
    id: "grocery-mini-mart-compact",
    name: "Mini Mart Compact",
    category: "grocery",
    description: "Two-column compact A5 bill for fast retail checkout lines.",
    paperSize: "A5",
    isThermal: false,
    themeColor: "emerald",
  },
  {
    id: "grocery-bazaar-bold",
    name: "Bazaar Bold",
    category: "grocery",
    description: "High-contrast bold header template suitable for busy wholesale grain markets.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "emerald",
  },
  {
    id: "grocery-super-saver",
    name: "Super Saver",
    category: "grocery",
    description: "Customer-centric receipt showing total savings, MRP vs billed rate, and next-visit coupon message.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "emerald",
  },

  // ----------------------------------------------------
  // General / Other Category (10 Templates)
  // ----------------------------------------------------
  {
    id: "general-corporate-clean",
    name: "Corporate Clean",
    category: "general",
    description: "Professional corporate tax invoice with elegant typography, complete GSTIN/PAN info, and bank details.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "blue",
    badge: "Corporate",
  },
  {
    id: "general-minimal-mono",
    name: "Minimal Mono",
    category: "general",
    description: "Architectural monochrome design with sharp borders, perfect for modern tech and design agencies.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "blue",
  },
  {
    id: "general-bold-header",
    name: "Bold Header",
    category: "general",
    description: "Prominent brand header block with high visual impact and strong company presence.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "blue",
  },
  {
    id: "general-classic-ledger",
    name: "Classic Ledger",
    category: "general",
    description: "Standard accounting ledger layout trusted by Indian Chartered Accountants and traders.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "blue",
  },
  {
    id: "general-modern-grid",
    name: "Modern Grid",
    category: "general",
    description: "Card-based structured grid separating seller, buyer, delivery address, and payment terms cleanly.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "blue",
  },
  {
    id: "general-freelancer-simple",
    name: "Freelancer Simple",
    category: "general",
    description: "Streamlined single-page invoice for consultants, developers, designers, and independent contractors.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "blue",
    badge: "Freelancers",
  },
  {
    id: "general-trade-invoice",
    name: "Trade Invoice",
    category: "general",
    description: "Heavy-duty commercial trade bill with E-way bill, vehicle number, dispatch details, and multi-slab tax grid.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "blue",
    badge: "B2B Trade",
  },
  {
    id: "general-service-pro",
    name: "Service Pro",
    category: "general",
    description: "Tailored for service businesses with SAC codes, hourly/monthly billing units, and project milestones.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "blue",
  },
  {
    id: "general-two-tone-tax",
    name: "Two-Tone Tax",
    category: "general",
    description: "Distinct two-tone header and footer balancing aesthetics with 100% statutory GST compliance.",
    paperSize: "A4",
    isThermal: false,
    themeColor: "blue",
  },
  {
    id: "general-compact-a5",
    name: "Compact A5",
    category: "general",
    description: "Clean half-page A5 invoice format that saves paper while providing all required tax fields.",
    paperSize: "A5",
    isThermal: false,
    themeColor: "blue",
    badge: "Compact A5",
  },
];

export function getTemplatesByCategory(category: CategoryId): TemplateMeta[] {
  return TEMPLATES.filter((t) => t.category === category);
}

export function getTemplateById(templateId: string): TemplateMeta | undefined {
  return TEMPLATES.find((t) => t.id === templateId);
}
